permalink: /:categories/:title
markdown: rdiscount

categories: parties, interviews, howto
defaultTile: &default_tile "media/sunnynook-default-tile.jpg"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      tile: *default_tile

sass:
  style: compressed

prose:
  rooturl: '_posts'
  siteurl: 'http://sunnynookdrive.github.io'
  media: 'media'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          help: "Select the site section in which to post"
          options:
            - name: 'Parties'
              value: 'parties'
            - name: 'Interviews'
              value: 'interviews'
            - name: 'How To'
              value: 'howto'
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Date (lenient format, Aug 30 1987 etc works)"
          value: "CURRENT_DATETIME"
      - name: "tile"
        field:
          element: "text"
          label: "Tile Image - 410pxw / 288pxh or larger is ok"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash Image - 1200pxw / 300pxh"
          value: ""
