permalink: pretty
markdown: rdiscount

categories: parties, interviews, howto
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      splash: null

prose:
  rooturl: '_posts'
  siteurl: 'http://sunnynookdrive.github.io'
  media: 'media'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          help: "Select the site section in which to post"
          options:
            - name: 'Parties'
              value: 'parties'
            - name: 'Interviews'
              value: 'interviews'
            - name: 'How To'
              value: 'howto'
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
